// Package index builds and renders the Markdown index table for a keep workspace.
package index

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/sidisinsane/keep-go/internal/document"
)

// IndexRow is a single entry in the index table.
type IndexRow struct {
	Slug    string
	Title   string
	Kind    string
	Status  string
	Summary string
}

// Build creates index rows from parsed documents.
func Build(results []document.ParseResult) []IndexRow {
	var rows []IndexRow
	for _, r := range results {
		if len(r.SchemaViolations) > 0 {
			continue
		}
		d := r.Document
		if d.Private {
			continue
		}
		rows = append(rows, IndexRow{
			Slug:    d.Slug,
			Title:   d.Title,
			Kind:    d.Kind,
			Status:  d.Status,
			Summary: d.Summary,
		})
	}
	sort.Slice(rows, func(i, j int) bool {
		return rows[i].Slug < rows[j].Slug
	})
	return rows
}

// Render returns the Markdown table string.
func Render(rows []IndexRow) string {
	var lines []string
	lines = append(lines, "<!-- Auto-generated by keep. Do not edit. -->")
	lines = append(lines, "")
	lines = append(lines, "| slug | title | kind | status | summary |")
	lines = append(lines, "| ---- | ----- | ---- | ------ | ------- |")
	for _, row := range rows {
		lines = append(lines, fmt.Sprintf("| %s | %s | %s | %s | %s |", row.Slug, row.Title, row.Kind, row.Status, row.Summary))
	}
	lines = append(lines, "")
	return strings.Join(lines, "\n")
}

// Write renders and writes the index file.
func Write(rows []IndexRow, path string) error {
	return os.WriteFile(path, []byte(Render(rows)), 0o644)
}
